<table class="table_dark">
	<tr><td colspan="10">Раунд 1</td></tr>
	<tr><td>Стол№01</td><td>	02-A</td><td>	03-D</td><td>	07-C</td><td>	08-D</td><td>	09-C</td><td>	16-A</td><td>	17-A</td><td>21-A</td><td>24-C</td><td>25-C</td></tr>
<tr><td>Стол№02</td><td>01-C</td><td>	04-C	</td><td>05-A</td><td>	09-D	</td><td>13-D</td><td>	14-C</td><td>	15-B</td><td>	16-D</td><td>	19-B</td><td>	23-A</td></tr>
<tr><td>Стол№03</td><td>	01-A	</td><td>03-B</td><td>	05-B</td><td>	08-C</td><td>	11-B</td><td>	12-D</td><td>	14-D</td><td>	20-A</td><td>	21-B	</td><td>23-C</td></tr>
<tr><td>Стол№04</td><td>	01-D</td><td>	06-A</td><td>	09-A	</td><td>10-C</td><td>	11-D</td><td>	14-A</td><td>	20-C</td><td>	22-C</td><td>	23-B</td><td>	24-B</td></tr>
<tr><td>Стол№05</td><td>	01-B</td><td>	05-C</td><td>	06-D</td><td>	13-A	</td><td>15-D</td><td>	17-B</td><td>	18-B</td><td>	20-B</td><td>	21-D</td><td>	25-A</td></tr>
<tr><td>Стол№06</td><td>	03-C</td><td>	04-D</td><td>	10-A</td><td>	12-B</td><td>	15-C</td><td>	18-A	</td><td>20-D</td><td>	22-A</td><td>	23-D</td><td>	25-D</td></tr>
<tr><td>Стол№07</td><td>	02-B</td><td>	04-B</td><td>	07-D</td><td>	10-D	</td><td>11-C	</td><td>12-A	</td><td>13-B	</td><td>15-A	</td><td>19-A</td><td>	21-C</td></tr>
<tr><td>Стол№08</td><td>	03-A</td><td>	04-A</td><td>	06-C</td><td>	09-B</td><td>	13-C</td><td>	14-B</td><td>	17-D</td><td>	19-D</td><td>	22-B</td><td>	24-D</td></tr>
<tr><td>Стол№09	</td><td>	02-C</td><td>	05-D</td><td>	06-B</td><td>	07-B</td><td>	08-B</td><td>	11-A</td><td>	12-C	</td><td>16-C</td><td>	18-D</td><td>	24-A</td></tr>
<tr><td>Стол№10	</td><td>	02-D	</td><td>07-A</td><td>	08-A</td><td>	10-B</td><td>	16-B</td><td>	17-C	</td><td>18-C</td><td>	19-C</td><td>	22-D</td><td>	25-B</td></tr>