<html>
<head>
	<link rel="stylesheet" type="text/css" href="templates/maska9.css"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<div id="css-menu-wrapper">
		<div id="css-menu">
		<ul>
			<li><a href="/maska9/?action=getPlacing">
				<span class="text-top">Рассадка игроков</span>
				<span class="text-bottom">Рассадка на столы</span></a></li>
			<li><a href="/maska9/?action=getTeams">
				<span class="text-top">Командный рейтинг</span>
				<span class="text-bottom">Статистика игроков</span>
			</a></li>
			
			
			<li><a href="/maska9/?action=insertGame">
				<span class="text-top">Добавить игру</span>
				<span class="text-bottom">Для организатора</span>
			</a></li>
			<li><a href="/maska9/?action=adminPanel">
				<span class="text-top">Рейтинг номинаций</span>
				<span class="text-bottom">Для организатора</span>
			</a></li>
			<li><a href="/maska9/?action=showGames">
				<span class="text-top">Подробно про игры</span>
				<span class="text-bottom">Для организатора</span>
			</a></li>
			
			
		</ul>
		</div>
</div>