<html>
<head>
	<link rel="stylesheet" type="text/css" href="templates/maska9.css"/>
	<meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
</head>
<div id="css-menu-wrapper">
		<div id="css-menu">
		<ul>
			<li><a href="#">
				<span class="text-top">Личный рейтинг </span>
				<span class="text-bottom">Рейтинг игроков</span>
			</a></li>
			<li><a href="#">
				<span class="text-top">Командный рейтинг</span>
				<span class="text-bottom">Рейтинг команд</span>
			</a></li>
			<li><a href="#">
				<span class="text-top">Подробный рейтинг</span>
				<span class="text-bottom">Инфа про игры</span>
			</a></li>
		</ul>
		</div>
</div>
